url: https://perkles.github.io/
paginate: 5

permalink: blog/:title

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/

  talks:
    output: true
    permalink: /talks/:title/

plugins:
  - jemoji
