url: https://perkles.github.io/
paginate: 5

permalink: blog/:title

collections:
  # portfolio:
  #   output: true
  #   permalink: /portfolio/:title/

  events:
    output: true
    permalink: /events/:title/

plugins:
  - jemoji
